#
# makefile
# KuoE0, 2014-03-15 00:01
#


topdown: knapsack.cpp
	g++ -o knapsack knapsack.cpp -DTOPDOWN

bottomup: knapsack.cpp
	g++ -o knapsack knapsack.cpp -DBOTTOMUP

bottomup1d: knapsack.cpp
	g++ -o knapsack knapsack.cpp -DBOTTOMUP1D

# vim:ft=make
#

